Improvements to user footer
SwiftcordApp/Swiftcord pull request #152
Opened 2023-05-15 17:39 UTC by BomberFish

- Use `gear` instead of `gearshape` for settings icon
- Limit custom status to one line like the official client

2023-05-15 17:44 UTC, Sjmarf commented
Icon comparison for convenience:

`gear`:

![gear@4x](https://github.com/SwiftcordApp/Swiftcord/assets/78750526/e737171d-881d-466b-93c0-4202d629cbb1)

`gearshape.fill`:

![gearshape fill@4x](https://github.com/SwiftcordApp/Swiftcord/assets/78750526/fcdb83d8-85c4-4c8b-bbd2-2b09a65deba0)

2023-05-15 17:58 UTC, BomberFish commented
I was (finally!) able to get Xcode builds working (updating to 14.3 final worked), so here's the user footer with my changes:

<img width="240" alt="Screenshot taken on 2023-05-15 at 13 55 39" src="https://github.com/SwiftcordApp/Swiftcord/assets/87151697/83039b2c-060c-4dd2-b362-efde75859833">

I was thinking of making the status a scrolling "marquee" text, but I felt that would be unnecessary as you could already see that in the user poppet.

2023-05-25 04:16 UTC, cryptoAlgorithm commented
Yup, I actually decided on the filled gear as I felt that matched Discord's style better. However it's clear we are after a more native look that flows with system apps, and as such I'll probably be merging this PR.

2023-05-25 08:41 UTC, cryptoAlgorithm requested changes
Please do not commit modifications to code signing settings (including development team) to prevent breaking CI builds and for consistency.

2023-05-25 08:41 UTC, cryptoAlgorithm commented on Swiftcord.xcodeproj/project.pbxproj
> +				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "-";
```suggestion
				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "Apple Development";
```

2023-05-25 08:41 UTC, cryptoAlgorithm commented on Swiftcord.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
```suggestion
				DEVELOPMENT_TEAM = Q382QLKDG3;
```

2023-05-25 08:41 UTC, cryptoAlgorithm commented on Swiftcord.xcodeproj/project.pbxproj
> +				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "-";
```suggestion
				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "Apple Development";
```

2023-05-25 08:41 UTC, cryptoAlgorithm commented on Swiftcord.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
```suggestion
				DEVELOPMENT_TEAM = Q382QLKDG3;
```

2023-05-25 08:41 UTC, cryptoAlgorithm commented on Swiftcord.xcodeproj/project.pbxproj
> +				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "-";
```suggestion
				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "Apple Development";
```

2023-05-25 08:41 UTC, cryptoAlgorithm commented on Swiftcord.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
```suggestion
				DEVELOPMENT_TEAM = Q382QLKDG3;
```

2023-05-25 08:41 UTC, cryptoAlgorithm requested changes
Please do not commit modifications to code signing settings (including development team) to prevent breaking CI builds and for consistency.

2023-05-25 09:14 UTC, merged